### ISSUE TITLE
Adding sounds

### ISSUE THREAD

**Issue by Wynadorn** [vincent0955/Visual-metronome#10]
It'd be great if we had the ability to play musical note on each color's tick.
For example the following melody can be used for 1.5t woodcutting: https://music-grid.surge.sh/#2048-0-256-0-0-512-0-1024-0-2048-0-256-0-0-512-0-1024-0-&300&classic

This could also support the ability to play sounds in more complex patterns (2 notes in 1t). Don't think this is currently available in any of the other metronome plugins.

All of this would be kinda odd in a plugin called **Visual** metronome however this currently is the best metronome implementation.

MS Paint design:
![image](https://user-images.githubusercontent.com/4095127/140618455-ac148af2-7d86-42ec-8fa8-62073712ac0f.png)

**Comment by vincent0955** [comment]
Good idea, but I think this is better suited for a maybe a separate metronome plugin since having another sound feature kind of defeats the purpose of having it called visual, and in the future if someone wants more features for the sound part of the plugin, it might clutter up the plugin a bit. So I hope you can understand why I want to keep this for visual purposes only. Thanks for the suggestion though, I appreciate it.
