### ISSUE TITLE
Feature request: Allow for more overhead tick number options

### ISSUE THREAD

**Issue by jefehlab** [vincent0955/Visual-metronome#41]
![image](https://github.com/user-attachments/assets/dea13115-9294-4b47-982c-870b90e16f1e)

Hello it would be awesome to have more than one tick count option. I was able to implement it crudely but this is the first time I code anything runelite related so it wasnt great.

It would really help, currently I am using both visual ticks and the visual metronome plugin to have more cycle lengths.

But the visual ticks plugin takes up a lot of space, I wish it could work like in the picture.

**Comment by vincent0955** [comment]
Hey I appreciate the suggestion and the pull request you made, however I'm not really looking to add new features as of right now, for a few reasons. Mainly because I don't want to clutter the plugin much more with features unless it is highly requested, and I think only a few people could use this feature. Also, I'm quite busy nowadays and don't want to spend much time on this project anymore. So yeah, sorry about that.

**Comment by JZomDev** [comment]
I think if you enabled the tick count by for it to trigger a recolor on the nth rotation of ticks that would be sufficient without the clutter. 

You could add a feature that makes it so the 5th tick is red and the 7th tick is blue rather than the 5th time the pattern has hit all numbers are red and the 7th cycle they're all blue. 

So meaning a tick count of 35 
5 red 
7 blue 
10 red
14 blue 
Etc 
35 could be either color, maybe 5's. 

That would allow jefeh's request to exist while not being more numbers on screen.

**Comment by vincent0955** [comment]
Decided over discord to implement the first idea and add the ability to add more overhead cycles, #43
