### ISSUE TITLE
Key to reset tick count

### ISSUE THREAD

**Issue by da1023** [vincent0955/Visual-metronome#5]
Hi,
Love the plugin, just wondering if a keybind for resetting the tick to 1 (aka the "tick") is possible? 
Thanks

**Comment by vincent0955** [comment]
Hey, I think it is possible, but keybinds in plugins are complicated since they might interfere with other controls or other plugins, so don't think I can add this as a feature, sorry. 
I could make the tick reset every time the config is changed though, which could help with timing the metronome, I don't know if that's also fits your needs or not. If it does, then I'll change it in the next update.

**Comment by da1023** [comment]
Hi Vincent, 
That makes sense, would every time the plugin turns on/off work?
Thanks for your time

**Comment by vincent0955** [comment]
Actually, I just checked and turning the plugin on and off already resets the tick, you can try it yourself. So I guess you can make use of that instead. 
If you want, I can still add the tick reset every time the config is changed as well, but that would have to wait until the next update.

**Comment by da1023** [comment]
oh thats nice! sorry I didn't realise - I can probably make do with this then, thanks.
